services:
  tdarr:
    container_name: tdarr
    image: ghcr.io/haveagitgat/tdarr:latest
    restart: unless-stopped
    network_mode: bridge
    ports:
      - 8265:8265 # webUI
      - 8266:8266 # server
    environment:
      - TZ=Asia/Kolkata
      - PUID=1000
      - PGID=1000
      - serverIP=0.0.0.0
    volumes:
      - /home/homeserver/app_configs/tdarr/server:/app/server
      - /home/homeserver/app_configs/tdarr/configs:/app/configs
      - /home/homeserver/app_configs/tdarr/logs:/app/logs
      - /mnt/fastmedia:/data
      - /home/homeserver/app_configs/tdarr/transcode_cache:/temp

  tdarr-node-pi:
    container_name: tdarr-node-pi
    image: ghcr.io/haveagitgat/tdarr_node:latest
    restart: unless-stopped
    network_mode: bridge
    environment:
      - TZ=Asia/Kolkata
      - PUID=1000
      - PGID=1000
      - nodeID=PiNode
      - nodeIP=0.0.0.0
      - serverIP=192.168.1.9 # Replace with your Pi's static IP
      - serverPort=8266
    volumes:
      - /home/homeserver/app_configs/tdarr/node_configs:/app/configs
      - /home/homeserver/app_configs/tdarr/logs:/app/logs
      - /mnt/fastmedia:/data
      - /home/homeserver/app_configs/tdarr/transcode_cache:/temp
