services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    hostname: pihole
    networks:
      - frontend
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      #- "80:80/tcp"
      #- "443:443/tcp"
    env_file:
      - .env
    environment:
      - TZ=Asia/Kolkata
      - FTLCONF_webserver_api_password=${PIHOLE_PASSWORD}
      - FTLCONF_dns_listeningMode=ALL
    volumes:
      - ./etc-pihole:/etc/pihole
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pihole-https.rule=Host(`pihole.jedarabale.space`)"
      - "traefik.http.routers.pihole-https.entrypoints=websecure"
      - "traefik.http.routers.pihole-https.tls.certresolver=cloudflare"
      - "traefik.http.services.pihole.loadbalancer.server.port=80"
      - "traefik.http.middlewares.pihole-prefix.addPrefix.prefix=/admin"
      - "traefik.http.routers.pihole-https.middlewares=pihole-prefix"
    restart: unless-stopped

networks:
  frontend:
    external: true
