version: "3"

services:
  warp-proxy:
    image: monius/docker-warp-socks:latest
    container_name: warp-proxy
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv4.conf.all.src_valid_mark=1
    ports:
      - "9091:9091" # Exposed port for the SOCKS5 proxy
    networks:
      - frontend
    restart: unless-stopped

networks:
  frontend:
    external: true
