services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    ports:                               # <--- ADDED THIS
      - "8000:8000"                      # <--- ADDED THIS (Portainer Edge Agent)
      - "9000:9000"                      # <--- ADDED THIS (Portainer HTTP Web UI)
      - "9443:9443"                      # <--- ADDED THIS (Portainer HTTPS Web UI)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    labels:
      # This entire section stays exactly the same for Cloudflare Internet access!
      - "traefik.enable=true"
      - "traefik.http.routers.portainer-https.rule=Host(`portainer.jedarabale.space`)"
      - "traefik.http.routers.portainer-https.entrypoints=websecure"
      - "traefik.http.routers.portainer-https.service=portainer"
      - "traefik.http.routers.portainer-https.tls.certresolver=cloudflare"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"
    networks:
      - frontend
    restart: unless-stopped

volumes:
  portainer_data:

networks:
  frontend:
    external: true
