version: '3.8'
services:
  pdf-compressor:
    image: charankumarbs/selfhost-pdf-compressor:latest
    networks:
      - proxy-net
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      update_config:
        order: stop-first
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.pdf-compressor-https.rule=Host(`pdf.jedarabale.space`)"
        - "traefik.http.routers.pdf-compressor-https.entrypoints=websecure"
        - "traefik.http.routers.pdf-compressor-https.service=pdf-compressor-service"
        - "traefik.http.routers.pdf-compressor-https.tls.certresolver=cloudflare"
        - "traefik.http.services.pdf-compressor-service.loadbalancer.server.port=8000"
        - "com.centurylinklabs.watchtower.enable=true"

networks:
  proxy-net:
    external: true
